default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", ENV.fetch("PGHOST", "localhost")) %>
  username: <%= ENV.fetch("DB_USERNAME", ENV.fetch("PGUSER", ENV["USER"])) %>
  password: <%= ENV.fetch("DB_PASSWORD", ENV["PGPASSWORD"]) %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_DATABASE", "tribetip_development") %>
  primary_replica:
    <<: *default
    host: <%= ENV.fetch("DB_REPLICA_HOST", ENV.fetch("DB_HOST", "localhost")) %>
    database: <%= ENV.fetch("DB_REPLICA_DATABASE", ENV.fetch("DB_DATABASE", "tribetip_development")) %>
    username: <%= ENV.fetch("DB_REPLICA_USERNAME", ENV.fetch("DB_USERNAME", ENV["USER"])) %>
    password: <%= ENV.fetch("DB_REPLICA_PASSWORD", ENV["DB_PASSWORD"]) %>
    replica: true

test:
  <<: *default
  database: tribetip_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV.fetch("DB_HOST", "localhost") %>
    database: <%= ENV.fetch("DB_DATABASE", "tribetip_production") %>
    username: <%= ENV.fetch("DB_USERNAME", "tribetip") %>
    password: <%= ENV["TRIBETIP_DATABASE_PASSWORD"] %>
  primary_replica:
    <<: *default
    host: <%= ENV.fetch("DB_REPLICA_HOST", ENV.fetch("DB_HOST", "localhost")) %>
    database: <%= ENV.fetch("DB_REPLICA_DATABASE", ENV.fetch("DB_DATABASE", "tribetip_production")) %>
    username: <%= ENV.fetch("DB_REPLICA_USERNAME", ENV.fetch("DB_USERNAME", "tribetip")) %>
    password: <%= ENV.fetch("DB_REPLICA_PASSWORD", ENV["TRIBETIP_DATABASE_PASSWORD"]) %>
    replica: true
  cache:
    <<: *primary_production
    database: tribetip_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tribetip_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tribetip_production_cable
    migrations_paths: db/cable_migrate
